//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: voldemort-admin.proto
// Note: requires additional types generated from: voldemort-client.proto
namespace Voldemort
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMetadataRequest")]
  public partial class GetMetadataRequest : global::ProtoBuf.IExtensible
  {
    public GetMetadataRequest() {}
    
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetMetadataResponse")]
  public partial class GetMetadataResponse : global::ProtoBuf.IExtensible
  {
    public GetMetadataResponse() {}
    

    private Voldemort.Versioned _version = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Versioned version
    {
      get { return _version; }
      set { _version = value; }
    }

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateMetadataRequest")]
  public partial class UpdateMetadataRequest : global::ProtoBuf.IExtensible
  {
    public UpdateMetadataRequest() {}
    
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }
    private Voldemort.Versioned _versioned;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"versioned", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Voldemort.Versioned versioned
    {
      get { return _versioned; }
      set { _versioned = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateMetadataResponse")]
  public partial class UpdateMetadataResponse : global::ProtoBuf.IExtensible
  {
    public UpdateMetadataResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PartitionEntry")]
  public partial class PartitionEntry : global::ProtoBuf.IExtensible
  {
    public PartitionEntry() {}
    
    private byte[] _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }
    private Voldemort.Versioned _versioned;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"versioned", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Voldemort.Versioned versioned
    {
      get { return _versioned; }
      set { _versioned = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePartitionEntriesRequest")]
  public partial class UpdatePartitionEntriesRequest : global::ProtoBuf.IExtensible
  {
    public UpdatePartitionEntriesRequest() {}
    
    private string _store;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store
    {
      get { return _store; }
      set { _store = value; }
    }
    private Voldemort.PartitionEntry _partition_entry;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"partition_entry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Voldemort.PartitionEntry partition_entry
    {
      get { return _partition_entry; }
      set { _partition_entry = value; }
    }

    private Voldemort.VoldemortFilter _filter = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.VoldemortFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdatePartitionEntriesResponse")]
  public partial class UpdatePartitionEntriesResponse : global::ProtoBuf.IExtensible
  {
    public UpdatePartitionEntriesResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoldemortFilter")]
  public partial class VoldemortFilter : global::ProtoBuf.IExtensible
  {
    public VoldemortFilter() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FetchPartitionEntriesRequest")]
  public partial class FetchPartitionEntriesRequest : global::ProtoBuf.IExtensible
  {
    public FetchPartitionEntriesRequest() {}
    
    private readonly global::System.Collections.Generic.List<int> _partitions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"partitions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> partitions
    {
      get { return _partitions; }
    }
  
    private string _store;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store
    {
      get { return _store; }
      set { _store = value; }
    }

    private Voldemort.VoldemortFilter _filter = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.VoldemortFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }

    private bool _fetch_values = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fetch_values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool fetch_values
    {
      get { return _fetch_values; }
      set { _fetch_values = value; }
    }

    private bool _fetch_master_entries = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fetch_master_entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool fetch_master_entries
    {
      get { return _fetch_master_entries; }
      set { _fetch_master_entries = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FetchPartitionEntriesResponse")]
  public partial class FetchPartitionEntriesResponse : global::ProtoBuf.IExtensible
  {
    public FetchPartitionEntriesResponse() {}
    

    private Voldemort.PartitionEntry _partition_entry = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"partition_entry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.PartitionEntry partition_entry
    {
      get { return _partition_entry; }
      set { _partition_entry = value; }
    }

    private byte[] _key = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] key
    {
      get { return _key; }
      set { _key = value; }
    }

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeletePartitionEntriesRequest")]
  public partial class DeletePartitionEntriesRequest : global::ProtoBuf.IExtensible
  {
    public DeletePartitionEntriesRequest() {}
    
    private string _store;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store
    {
      get { return _store; }
      set { _store = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _partitions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"partitions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> partitions
    {
      get { return _partitions; }
    }
  

    private Voldemort.VoldemortFilter _filter = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.VoldemortFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeletePartitionEntriesResponse")]
  public partial class DeletePartitionEntriesResponse : global::ProtoBuf.IExtensible
  {
    public DeletePartitionEntriesResponse() {}
    

    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitiateFetchAndUpdateRequest")]
  public partial class InitiateFetchAndUpdateRequest : global::ProtoBuf.IExtensible
  {
    public InitiateFetchAndUpdateRequest() {}
    
    private int _node_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"node_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int node_id
    {
      get { return _node_id; }
      set { _node_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _partitions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"partitions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> partitions
    {
      get { return _partitions; }
    }
  
    private string _store;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store
    {
      get { return _store; }
      set { _store = value; }
    }

    private Voldemort.VoldemortFilter _filter = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"filter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.VoldemortFilter filter
    {
      get { return _filter; }
      set { _filter = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsyncOperationStatusRequest")]
  public partial class AsyncOperationStatusRequest : global::ProtoBuf.IExtensible
  {
    public AsyncOperationStatusRequest() {}
    
    private int _request_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsyncOperationStopRequest")]
  public partial class AsyncOperationStopRequest : global::ProtoBuf.IExtensible
  {
    public AsyncOperationStopRequest() {}
    
    private int _request_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsyncOperationStopResponse")]
  public partial class AsyncOperationStopResponse : global::ProtoBuf.IExtensible
  {
    public AsyncOperationStopResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsyncOperationListRequest")]
  public partial class AsyncOperationListRequest : global::ProtoBuf.IExtensible
  {
    public AsyncOperationListRequest() {}
    
    private int _request_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }
    private bool _show_complete;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"show_complete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool show_complete
    {
      get { return _show_complete; }
      set { _show_complete = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsyncOperationListResponse")]
  public partial class AsyncOperationListResponse : global::ProtoBuf.IExtensible
  {
    public AsyncOperationListResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _request_ids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"request_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> request_ids
    {
      get { return _request_ids; }
    }
  

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitiateRebalanceNodeRequest")]
  public partial class InitiateRebalanceNodeRequest : global::ProtoBuf.IExtensible
  {
    public InitiateRebalanceNodeRequest() {}
    
    private int _stealer_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stealer_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stealer_id
    {
      get { return _stealer_id; }
      set { _stealer_id = value; }
    }
    private int _donor_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"donor_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int donor_id
    {
      get { return _donor_id; }
      set { _donor_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _partitions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"partitions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> partitions
    {
      get { return _partitions; }
    }
  
    private int _attempt;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attempt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attempt
    {
      get { return _attempt; }
      set { _attempt = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _deletePartitions = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"deletePartitions", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> deletePartitions
    {
      get { return _deletePartitions; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _unbalanced_store = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"unbalanced_store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> unbalanced_store
    {
      get { return _unbalanced_store; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AsyncOperationStatusResponse")]
  public partial class AsyncOperationStatusResponse : global::ProtoBuf.IExtensible
  {
    public AsyncOperationStatusResponse() {}
    

    private int _request_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"request_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int request_id
    {
      get { return _request_id; }
      set { _request_id = value; }
    }

    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }

    private string _status = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string status
    {
      get { return _status; }
      set { _status = value; }
    }

    private bool _complete = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"complete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool complete
    {
      get { return _complete; }
      set { _complete = value; }
    }

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TruncateEntriesRequest")]
  public partial class TruncateEntriesRequest : global::ProtoBuf.IExtensible
  {
    public TruncateEntriesRequest() {}
    
    private string _store;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store
    {
      get { return _store; }
      set { _store = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TruncateEntriesResponse")]
  public partial class TruncateEntriesResponse : global::ProtoBuf.IExtensible
  {
    public TruncateEntriesResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStoreRequest")]
  public partial class AddStoreRequest : global::ProtoBuf.IExtensible
  {
    public AddStoreRequest() {}
    
    private string _storeDefinition;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"storeDefinition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string storeDefinition
    {
      get { return _storeDefinition; }
      set { _storeDefinition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddStoreResponse")]
  public partial class AddStoreResponse : global::ProtoBuf.IExtensible
  {
    public AddStoreResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteStoreRequest")]
  public partial class DeleteStoreRequest : global::ProtoBuf.IExtensible
  {
    public DeleteStoreRequest() {}
    
    private string _storeName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"storeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string storeName
    {
      get { return _storeName; }
      set { _storeName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteStoreResponse")]
  public partial class DeleteStoreResponse : global::ProtoBuf.IExtensible
  {
    public DeleteStoreResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FetchStoreRequest")]
  public partial class FetchStoreRequest : global::ProtoBuf.IExtensible
  {
    public FetchStoreRequest() {}
    
    private string _store_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store_name
    {
      get { return _store_name; }
      set { _store_name = value; }
    }
    private string _store_dir;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"store_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store_dir
    {
      get { return _store_dir; }
      set { _store_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapStoreRequest")]
  public partial class SwapStoreRequest : global::ProtoBuf.IExtensible
  {
    public SwapStoreRequest() {}
    
    private string _store_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store_name
    {
      get { return _store_name; }
      set { _store_name = value; }
    }
    private string _store_dir;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"store_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store_dir
    {
      get { return _store_dir; }
      set { _store_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwapStoreResponse")]
  public partial class SwapStoreResponse : global::ProtoBuf.IExtensible
  {
    public SwapStoreResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RollbackStoreRequest")]
  public partial class RollbackStoreRequest : global::ProtoBuf.IExtensible
  {
    public RollbackStoreRequest() {}
    
    private string _store_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string store_name
    {
      get { return _store_name; }
      set { _store_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RollbackStoreResponse")]
  public partial class RollbackStoreResponse : global::ProtoBuf.IExtensible
  {
    public RollbackStoreResponse() {}
    

    private Voldemort.Error _error = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.Error error
    {
      get { return _error; }
      set { _error = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoldemortAdminRequest")]
  public partial class VoldemortAdminRequest : global::ProtoBuf.IExtensible
  {
    public VoldemortAdminRequest() {}
    
    private Voldemort.AdminRequestType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Voldemort.AdminRequestType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private Voldemort.GetMetadataRequest _get_metadata = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"get_metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.GetMetadataRequest get_metadata
    {
      get { return _get_metadata; }
      set { _get_metadata = value; }
    }

    private Voldemort.UpdateMetadataRequest _update_metadata = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"update_metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.UpdateMetadataRequest update_metadata
    {
      get { return _update_metadata; }
      set { _update_metadata = value; }
    }

    private Voldemort.UpdatePartitionEntriesRequest _update_partition_entries = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"update_partition_entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.UpdatePartitionEntriesRequest update_partition_entries
    {
      get { return _update_partition_entries; }
      set { _update_partition_entries = value; }
    }

    private Voldemort.FetchPartitionEntriesRequest _fetch_partition_entries = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fetch_partition_entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.FetchPartitionEntriesRequest fetch_partition_entries
    {
      get { return _fetch_partition_entries; }
      set { _fetch_partition_entries = value; }
    }

    private Voldemort.DeletePartitionEntriesRequest _delete_partition_entries = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"delete_partition_entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.DeletePartitionEntriesRequest delete_partition_entries
    {
      get { return _delete_partition_entries; }
      set { _delete_partition_entries = value; }
    }

    private Voldemort.InitiateFetchAndUpdateRequest _initiate_fetch_and_update = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"initiate_fetch_and_update", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.InitiateFetchAndUpdateRequest initiate_fetch_and_update
    {
      get { return _initiate_fetch_and_update; }
      set { _initiate_fetch_and_update = value; }
    }

    private Voldemort.AsyncOperationStatusRequest _async_operation_status = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"async_operation_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.AsyncOperationStatusRequest async_operation_status
    {
      get { return _async_operation_status; }
      set { _async_operation_status = value; }
    }

    private Voldemort.InitiateRebalanceNodeRequest _initiate_rebalance_node = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"initiate_rebalance_node", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.InitiateRebalanceNodeRequest initiate_rebalance_node
    {
      get { return _initiate_rebalance_node; }
      set { _initiate_rebalance_node = value; }
    }

    private Voldemort.AsyncOperationStopRequest _async_operation_stop = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"async_operation_stop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.AsyncOperationStopRequest async_operation_stop
    {
      get { return _async_operation_stop; }
      set { _async_operation_stop = value; }
    }

    private Voldemort.AsyncOperationListRequest _async_operation_list = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"async_operation_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.AsyncOperationListRequest async_operation_list
    {
      get { return _async_operation_list; }
      set { _async_operation_list = value; }
    }

    private Voldemort.TruncateEntriesRequest _truncate_entries = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"truncate_entries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.TruncateEntriesRequest truncate_entries
    {
      get { return _truncate_entries; }
      set { _truncate_entries = value; }
    }

    private Voldemort.AddStoreRequest _add_store = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"add_store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.AddStoreRequest add_store
    {
      get { return _add_store; }
      set { _add_store = value; }
    }

    private Voldemort.DeleteStoreRequest _delete_store = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"delete_store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.DeleteStoreRequest delete_store
    {
      get { return _delete_store; }
      set { _delete_store = value; }
    }

    private Voldemort.FetchStoreRequest _fetch_store = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"fetch_store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.FetchStoreRequest fetch_store
    {
      get { return _fetch_store; }
      set { _fetch_store = value; }
    }

    private Voldemort.SwapStoreRequest _swap_store = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"swap_store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.SwapStoreRequest swap_store
    {
      get { return _swap_store; }
      set { _swap_store = value; }
    }

    private Voldemort.RollbackStoreRequest _rollback_store = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"rollback_store", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Voldemort.RollbackStoreRequest rollback_store
    {
      get { return _rollback_store; }
      set { _rollback_store = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"AdminRequestType")]
    public enum AdminRequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_METADATA", Value=0)]
      GET_METADATA = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_METADATA", Value=1)]
      UPDATE_METADATA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_PARTITION_ENTRIES", Value=2)]
      UPDATE_PARTITION_ENTRIES = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FETCH_PARTITION_ENTRIES", Value=3)]
      FETCH_PARTITION_ENTRIES = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_PARTITION_ENTRIES", Value=4)]
      DELETE_PARTITION_ENTRIES = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INITIATE_FETCH_AND_UPDATE", Value=5)]
      INITIATE_FETCH_AND_UPDATE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASYNC_OPERATION_STATUS", Value=6)]
      ASYNC_OPERATION_STATUS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INITIATE_REBALANCE_NODE", Value=7)]
      INITIATE_REBALANCE_NODE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASYNC_OPERATION_STOP", Value=8)]
      ASYNC_OPERATION_STOP = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASYNC_OPERATION_LIST", Value=9)]
      ASYNC_OPERATION_LIST = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRUNCATE_ENTRIES", Value=10)]
      TRUNCATE_ENTRIES = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD_STORE", Value=11)]
      ADD_STORE = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_STORE", Value=12)]
      DELETE_STORE = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FETCH_STORE", Value=13)]
      FETCH_STORE = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SWAP_STORE", Value=14)]
      SWAP_STORE = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROLLBACK_STORE", Value=15)]
      ROLLBACK_STORE = 15
    }
  
}
